service: serverless-webpack

plugins:
  - serverless-webpack

package:
  individually: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: post
          path: hello/

  consumer:
    handler: consumer.main
    events:
      - http:
          method: post
          path: consumer/